apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifescope-api
  namespace: lifescope
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lifescope-api
  template:
    metadata:
      labels:
        app: lifescope-api
    spec:
      serviceAccountName: lifescope
      containers:
        - name: lifescope-api
          image: lifescopelabs/lifescope-api:v4.0.6
          ports:
            - containerPort: 3000
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
          volumeMounts:
            - mountPath: "/usr/src/lifescope-api/config/tmp"
              name: lifescope-api-prod-config
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /usr/src/lifescope-api/config/tmp/production.json /usr/src/lifescope-api/config/production.json
          imagePullPolicy: IfNotPresent
      dnsPolicy: Default
      volumes:
        - name: lifescope-api-prod-config
          secret:
            secretName: lifescope-api-prod-config
      $patch: replace
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lifescope-api-ingress-master
  namespace: lifescope
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
spec:
  tls:
    - hosts:
        - api.lifescope.io
      secretName: lifescope-secret
  rules:
    - host: api.lifescope.io
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lifescope-api-ingress-location-upload-minion
  namespace: lifescope
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/client-max-body-size: "2000m"
spec:
  rules:
    - host: api.lifescope.io
      http:
        paths:
          - backend:
              serviceName: lifescope-api
              servicePort: 3000
            path: /location/upload_file
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lifescope-api-ingress-ws-minion
  namespace: lifescope
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/websocket-services: "lifescope-api-ws"
spec:
  rules:
    - host: api.lifescope.io
      http:
        paths:
          - backend:
              serviceName: lifescope-api-ws
              servicePort: 3001
            path: /subscriptions
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lifescope-api-ingress-main-minion
  namespace: lifescope
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: api.lifescope.io
      http:
        paths:
          - backend:
              serviceName: lifescope-api
              servicePort: 3000
            path: /