{{- if .Values.client.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xrsocial.client.fullname" . }}
  labels:
    {{- include "xrsocial.client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      {{- include "xrsocial.client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xrsocial.client.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/client-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.client.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xrsocial.client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.client.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.client.securityContext | nindent 12 }}
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "xrsocial.client.fullname" . }}
                optional: true
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              scheme: HTTPS
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              scheme: HTTPS
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
      {{- with .Values.client.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.client.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.client.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}