{{- if (.Values.builder).enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "xrengine.builder.fullname" . }}
  labels:
    {{- include "xrengine.builder.labels" . | nindent 4 }}
data:
{{- if .Values.builder.extraEnv }}
{{ toYaml .Values.builder.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.api.extraEnv }}
{{ toYaml .Values.api.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.instanceserver.extraEnv }}
{{ toYaml .Values.instanceserver.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.client.extraEnv }}
{{ toYaml .Values.client.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.builder.config }}
  NODE_CONFIG: '{{ mustToJson .Values.builder.config }}'
{{- end }}
{{- end -}}
