{{- if (.Values.analytics).enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xrengine.analytics.fullname" . }}
  labels:
    {{- include "xrengine.analytics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.analytics.replicaCount }}
  selector:
    matchLabels:
      {{- include "xrengine.analytics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xrengine.analytics.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/analytics-server-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.analytics.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xrengine.analytics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.analytics.podSecurityContext | nindent 8 }}
      {{- $releaseName := .Release.Name }}
      {{ if not (empty .Values.release) }}
      {{- $releaseName = .Values.release.name | default .Release.Name }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.analytics.securityContext | nindent 12 }}
          image: "{{ .Values.analytics.image.repository }}:{{ .Values.analytics.image.tag }}"
          imagePullPolicy: {{ .Values.analytics.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "xrengine.analytics.fullname" . }}
                optional: true
          env:
            - name: SERVER_MODE
              value: "analytics"
            - name: KUBERNETES
              value: "true"
            {{ if .Values.sql }}
            - name: MYSQL_USER
              value: {{ .Values.sql.user }}
            - name: MYSQL_DATABASE
              value: {{ .Values.sql.database }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.sql.password | quote }}
            - name: MYSQL_HOST
              value: {{ .Values.sql.host | quote }}
            - name: MYSQL_PORT
              value: {{ .Values.sql.port | quote }}
            {{ else if .Values.mariadb }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.db.user }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.db.name }}
            - name: MYSQL_PASSWORD
              {{- if not .Values.mariadb.enabled }}
              value: {{ .Values.mariadb.db.password | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.existingSecret }}
                  name: {{ .Values.mariadb.existingSecret }}
                  {{- else }}
                  name: {{ template "xrengine.mariadb.fullname" . }}
                  {{- end }}
                  key: mariadb-password
              {{- end }}
            - name: MYSQL_HOST
              value: {{ .Values.mariadb.externalHost }}
            - name: MYSQL_PORT
              value: {{ .Values.mariadb.externalPort | quote }}
            {{ else }}
            - name: MYSQL_USER
              value: server
            - name: MYSQL_DATABASE
              value: xrengine
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_HOST
              value: host.minikube.internal
            - name: MYSQL_PORT
              value: 3306
            {{ end }}
            - name: REDIS_ENABLED
              value: "true"
            - name: REDIS_ADDRESS
              value: "$({{ $releaseName | upper }}_REDIS_MASTER_SERVICE_HOST)"
            - name: REDIS_PORT
              value: "$({{ $releaseName | upper }}_REDIS_MASTER_SERVICE_PORT)"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $releaseName }}-redis
                  key: redis-password
            - name: RELEASE_NAME
              value: {{ $releaseName }}
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.analytics.resources | nindent 12 }}
      {{- with .Values.analytics.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.analytics.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.analytics.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
