{{- if .Values.media.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "xrsocial.media.fullname" . }}
  labels:
    {{- include "xrsocial.media.labels" . | nindent 4 }}
data:
{{- if .Values.media.extraEnv }}
{{ toYaml .Values.media.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.media.config }}
  NODE_CONFIG: '{{ mustToJson .Values.media.config }}'
{{- end }}
{{- end -}}
