version: '2.3'
services:
  rts:    #xrengine-realtime-server
    build: 
      context: ../xrsocial-realtime-server
    image: xrengine/realtime-server
    restart: always
    environment:
      NAF_LISTEN_PORT: 8081
    ports:
      - '8081:8081'
      - '9229:9229'

  server:
    build: 
      context: ../xrsocial
    image: xrengine/server
    restart: always
    environment:
      PORT: 3030
      # take care, db not 127.0.0.1, because compose uses an intenal DNS
      MYSQL_URL: mysql://server:password@db:3306/xrengine 
    ports:
      - '3030:3030'
    depends_on: 
      - db
  
  client:
    build: 
      context: ../xrsocial-client
    image: xrengine/client
    environment:
        API_SERVER: https://127.0.0.1:3030
        SITE_TITLE: XREngine
        SITE_DESC: Connected Worlds for Everyone
        APP_ENV: dev
    restart: always
    ports:
      - '3000:3000'
 
  # DB Server
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xrengine-root-pa$$w0rd
      MYSQL_DATABASE: xrengine
      MYSQL_USER: server
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
 

  # lets you view the database
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
