version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: xrengine_test
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_SSL=${DATABASE_SSL}
      - FOREST_AUTH_SECRET=${FOREST_AUTH_SECRET}
      - FOREST_ENV_SECRET=${FOREST_ENV_SECRET}
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    volumes:
      - ./:/usr/src/app
