# Default values for xrengine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domain: xrengine.dev

release:
  name: dev

director:
  enabled: true
  name: xrengine-matchmaking-director

  replicaCount: 1
  image:
    repository: lagunalabs/xrengine-matchmaking-director
    tag: latest
    pullPolicy: IfNotPresent

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 3030

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: api.social.local
        paths: ["/"]
    # tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local


  serviceAccount:
    create: true
    annotations: {}
    name:

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  securityContext: {}

  # Extra Environment variables to configure xrsocial
  extraEnv:

matchfunction:
  enabled: true
  name: xrengine-matchmaking-matchfunction

  replicaCount: 1
  image:
    repository: lagunalabs/xrengine-matchmaking-matchfunction
    tag: latest
    pullPolicy: IfNotPresent

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 50502

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: api.social.local
        paths: ["/"]
    # tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local


  serviceAccount:
    create: true
    annotations: {}
    name:

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  securityContext: {}

  # Extra Environment variables to configure xrsocial
  extraEnv:
