
version: '2.3'
services:
  db:
    image: mariadb:10.7
    container_name: xrengine_db
    environment:
      MYSQL_ROOT_PASSWORD: xrengine-root-pa$$w0rd
      MYSQL_DATABASE: xrengine
      MYSQL_USER: server
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
  redis:
    image: redis
    container_name: xrengine_redis
    command: redis-server
    ports:
      - '6379:6379'
