name: prod-deploy
on:
  push:
    branches:
      [master]
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Setup Helm
        run: scripts/setup_helm_builder.sh
      - name: Setup AWS
        run: scripts/setup_aws_builder.sh $AWS_ACCESS_KEY $AWS_SECRET $AWS_REGION $CLUSTER_NAME
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      - name: Space debug
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Build Docker Image
        run: bash scripts/build_docker_builder.sh prod $DOCKER_LABEL $AWS_REGION
        env:
          DOCKER_LABEL: ${{ secrets.DOCKER_LABEL }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_URL: ${{ secrets.ECR_URL }}
      - name: npm-install 'cli' and 'aws-sdk'
        run: npm install cli aws-sdk
      - name: Publish to Elastic Container Registry
        run: bash scripts/publish_ecr_builder.sh prod $GITHUB_SHA $DOCKER_LABEL $AWS_REGION
        env:
          DOCKER_LABEL: ${{ secrets.DOCKER_LABEL }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_URL: ${{ secrets.ECR_URL }}
      - name: Deploy to EKS
        run: bash scripts/deploy_builder.sh prod $GITHUB_SHA
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_LABEL: ${{ secrets.DOCKER_LABEL }}
      - name: Job succeeded
        if: always()
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
          run: |
            git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
            bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
          shell: bash